# Generated by Django 3.1.5 on 2021-01-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteca',
            name='dispositionNumber',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='affairId',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='date',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='dispositionTitle',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='dispositionTypeId',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='legislationTranscriptCopy',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='legislationTranscriptOriginal',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='pageNumbers',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='place',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='volume',
            field=models.CharField(blank=True, max_length=155),
        ),
    ]
