# Generated by Django 3.1.5 on 2021-02-09 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispositions', '0001_initial'),
        ('affair', '0002_affair_created_at'),
        ('search', '0002_auto_20210130_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblioteca',
            name='affairId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='affair.affair'),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='dispositionTypeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispositions.disposition'),
        ),
    ]
