# Generated by Django 3.1.5 on 2021-03-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20210209_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblioteca',
            name='dispositionNumber',
            field=models.IntegerField(blank=True),
        ),
    ]
