# Generated by Django 3.1.6 on 2021-02-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositionType', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
