# Generated by Django 3.1.6 on 2021-02-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affair', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affair',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
